version: 2.1
jobs:
  Build:
    docker:
      - image: columbiasedwards/plt
    steps:
      - checkout
      - run:
          name: Build ocaml
          command: |
            make all
            make clean
  # Check that HelloWorld Works ok from our code
  Run-Tests:
    docker:
      - image: columbiasedwards/plt
    steps:
      - checkout
      - run:
          name: Run Hello World Test
          command: |
            make all
            ./hello_world.sh
workflows:
  version: 2
  Build_Test:
    jobs:
      - Build
      - Run-Tests
